services:
  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./portal/.env.local
    restart: always

  whatsapp-bot:
    build:
      context: .
      dockerfile: whatsapp_bot.Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    restart: always
