-- ==============================================================================
-- FASE 2: MIGRACIÓN E INDEPENDENCIA DE SHAREPOINT
-- Objetivo: Sincronizar contadores Autoincrementales (Inteligente)
-- ==============================================================================

-- ¡El script definitivo a prueba de balas! 
-- Verifica dinámicamente si la tabla es Identity nativa (como ordenes_publicidad).
-- Si no lo es (como clientes), la transforma a Identity. Y finalmente ajusta los valores máximos.

DO $$
DECLARE
    t_name TEXT;
    max_val INT;
    has_identity BOOLEAN;
    tablas TEXT[] := ARRAY['clientes', 'vendedores', 'programas', 'ordenes_publicidad', 'pagos', 'tv', 'unidades_negocio', 'usuarios'];
BEGIN
    FOREACH t_name IN ARRAY tablas LOOP
        -- Comprobar que la tabla exista
        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = t_name) THEN
            
            -- Revisar si ya era Identity previamente o no
            SELECT (is_identity = 'YES') INTO has_identity 
            FROM information_schema.columns 
            WHERE table_schema = 'public' AND table_name = t_name AND column_name = 'id';
            
            -- Si no es Identity explícita (error 55000), agregar la cualidad estructural
            IF has_identity IS FALSE THEN
                EXECUTE 'ALTER TABLE ' || quote_ident(t_name) || ' ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY';
            END IF;

            -- Averiguar el máximo ID usado (o 1 si está vacía)
            EXECUTE 'SELECT COALESCE(MAX(id), 1) FROM ' || quote_ident(t_name) INTO max_val;
            
            -- Sincronizar reiniciando la base al próximo registro futuro
            EXECUTE 'ALTER TABLE ' || quote_ident(t_name) || ' ALTER COLUMN id RESTART WITH ' || (max_val + 1);
            
        END IF;
    END LOOP;
END $$;

-- FIN.
