-- 1. CLIENTES (sin dependencias)
CREATE TABLE IF NOT EXISTS clientes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre           TEXT,
    nombre_comercial TEXT,
    razon_social     TEXT,
    mail             TEXT,
    posicion_iva     TEXT,
    cuit             TEXT,
    rubro            TEXT,
    old_id           INTEGER,
    activo           BOOLEAN DEFAULT TRUE,
    created          TIMESTAMP,
    modified         TIMESTAMP
);

-- 2. VENDEDORES (sin dependencias)
CREATE TABLE IF NOT EXISTS vendedores (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre    TEXT,
    apellido  TEXT,
    dni       TEXT,
    direccion TEXT,
    mail      TEXT,
    telefono  TEXT,
    old_id    INTEGER,
    activo    BOOLEAN DEFAULT TRUE,
    created   TIMESTAMP,
    modified  TIMESTAMP
);

-- 3. PROGRAMAS (sin dependencias)
CREATE TABLE IF NOT EXISTS programas (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title    TEXT,
    medio    TEXT,
    inicio   TEXT,
    fin      TEXT,
    activo   BOOLEAN DEFAULT TRUE,
    created  TIMESTAMP,
    modified TIMESTAMP
);

-- 4. USUARIOS (sin dependencias)
CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre        TEXT,
    apellido      TEXT,
    email         TEXT UNIQUE,
    password_hash TEXT,
    administrador BOOLEAN DEFAULT FALSE,
    activo        BOOLEAN DEFAULT TRUE,
    created       TIMESTAMP,
    modified      TIMESTAMP
);

-- 5. ORDENES DE PUBLICIDAD (depende de clientes y vendedores)
CREATE TABLE IF NOT EXISTS ordenes_publicidad (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    op              TEXT UNIQUE NOT NULL,
    numero_factura  TEXT,
    empresa         TEXT,
    fecha_orden     DATE,
    cliente_id      INTEGER REFERENCES clientes(id) ON DELETE SET NULL,
    cliente_nombre  TEXT,
    vendedor_id     INTEGER REFERENCES vendedores(id) ON DELETE SET NULL,
    vendedor_nombre TEXT,
    programa_nombre TEXT, -- Agregado para cumplir con indicación del usuario
    clasificacion   TEXT,
    venta_combo     BOOLEAN DEFAULT FALSE,
    inicio_pauta    DATE,
    fin_pauta       DATE,
    modulos_papel   TEXT,
    medidas_digital TEXT,
    anio            INTEGER,
    dia             TEXT,
    mes             TEXT,
    tipo_factura    TEXT,
    es_canje        BOOLEAN DEFAULT FALSE,
    importe_total   NUMERIC(12,2),
    iva             NUMERIC(12,2),
    importe_sin_iva NUMERIC(12,2),
    fecha_factura   DATE,
    esta_facturado  BOOLEAN DEFAULT FALSE,
    fecha_creacion  DATE,
    activo          BOOLEAN DEFAULT TRUE,
    created         TIMESTAMP,
    modified        TIMESTAMP
);

-- 6. PAGOS (depende de ordenes_publicidad)
CREATE TABLE IF NOT EXISTS pagos (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    op_id             INTEGER REFERENCES ordenes_publicidad(id) ON DELETE SET NULL,
    op_numero         TEXT, -- Corresponde al campo "OP" en SharePoint
    fecha_pago        DATE,
    importe_pago      NUMERIC(12,2),
    total_sin_iva     NUMERIC(12,2),
    comision          NUMERIC(12,2),
    importe_comision  NUMERIC(12,2),
    fecha_liquidacion DATE,
    esta_liquidado    BOOLEAN DEFAULT FALSE,
    vendedor          TEXT,
    iva               NUMERIC(12,2),
    recibo_numero     INTEGER,
    saldo             NUMERIC(12,2),
    medio_pago        TEXT,
    cliente           TEXT,
    activo            BOOLEAN DEFAULT TRUE,
    created           TIMESTAMP,
    modified          TIMESTAMP
);

-- 7. TV
CREATE TABLE IF NOT EXISTS tv (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    op_numero       TEXT, -- Renombrado de op_ref para consistencia
    op_id           INTEGER REFERENCES ordenes_publicidad(id) ON DELETE CASCADE,
    programa_id     INTEGER REFERENCES programas(id) ON DELETE SET NULL,
    programa_nombre TEXT,
    tipo            TEXT,
    importe_total   NUMERIC(12,2),
    iva             NUMERIC(12,2),
    importe_sin_iva NUMERIC(12,2),
    segundos        NUMERIC(8,2),
    valor_segundo   NUMERIC(12,4),
    activo          BOOLEAN DEFAULT TRUE,
    created         TIMESTAMP,
    modified        TIMESTAMP
);

-- 8. UNIDADES DE NEGOCIO
CREATE TABLE IF NOT EXISTS unidades_negocio (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    op_numero       TEXT, -- Renombrado de op_ref para consistencia
    op_id           INTEGER REFERENCES ordenes_publicidad(id) ON DELETE CASCADE,
    unidad_negocio  TEXT,
    importe_total   NUMERIC(12,2),
    importe_sin_iva NUMERIC(12,2),
    iva             NUMERIC(12,2),
    fecha_creacion  DATE,
    activo          BOOLEAN DEFAULT TRUE,
    created         TIMESTAMP,
    modified        TIMESTAMP
);

-- 9. SYNC LOG (Corregido para coincidir con el script Python)
CREATE TABLE IF NOT EXISTS sync_log (
    id                     SERIAL PRIMARY KEY,
    fecha_inicio           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_fin              TIMESTAMP,
    estado                 TEXT, -- 'PROCESANDO', 'EXITO', 'ERROR'
    registros_procesados   INTEGER DEFAULT 0,
    detalle                TEXT
);

-- 10. SYNC CONFIG
CREATE TABLE IF NOT EXISTS sync_config (
    clave TEXT PRIMARY KEY,
    valor TEXT
);
INSERT INTO sync_config VALUES ('last_sync', '2000-01-01T00:00:00Z')
ON CONFLICT (clave) DO NOTHING;

-- ÍNDICES DE PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_op_op ON ordenes_publicidad(op);
CREATE INDEX IF NOT EXISTS idx_op_cliente ON ordenes_publicidad(cliente_id);
CREATE INDEX IF NOT EXISTS idx_op_vendedor ON ordenes_publicidad(vendedor_id);
CREATE INDEX IF NOT EXISTS idx_op_modified ON ordenes_publicidad(modified);

CREATE INDEX IF NOT EXISTS idx_pagos_op_id ON pagos(op_id);
CREATE INDEX IF NOT EXISTS idx_pagos_op_numero ON pagos(op_numero);
CREATE INDEX IF NOT EXISTS idx_pagos_modified ON pagos(modified);

CREATE INDEX IF NOT EXISTS idx_tv_op_id ON tv(op_id);
CREATE INDEX IF NOT EXISTS idx_tv_op_numero ON tv(op_numero);
CREATE INDEX IF NOT EXISTS idx_tv_modified ON tv(modified);

CREATE INDEX IF NOT EXISTS idx_un_op_id ON unidades_negocio(op_id);
CREATE INDEX IF NOT EXISTS idx_un_op_numero ON unidades_negocio(op_numero);
CREATE INDEX IF NOT EXISTS idx_un_modified ON unidades_negocio(modified);

CREATE INDEX IF NOT EXISTS idx_sync_log_fecha ON sync_log(fecha_inicio);

-- ÍNDICES GIN PARA BÚSQUEDA DE TEXTO RÁPIDO (pg_trgm)
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS idx_op_cliente_nombre_trgm ON ordenes_publicidad USING gin (cliente_nombre gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_op_vendedor_nombre_trgm ON ordenes_publicidad USING gin (vendedor_nombre gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_clientes_nombre_trgm ON clientes USING gin (nombre gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_vendedores_nombre_trgm ON vendedores USING gin (nombre gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_unidades_empresa_trgm ON unidades_negocio USING gin (unidad_negocio gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_tv_programa_nombre_trgm ON tv USING gin (programa_nombre gin_trgm_ops);
